[Variables]

Bands=64
; Number of peaks - Activate Ocean\GenerateBands.ini skin after changing this value

Color=74, 174, 207

Width=1000
Height=600

LineWidth=5

AverageSize=12
; Average sound levels over time to provide continuity

LoudnessEqualization=1
; Increases visibility for quiet audio sources when applicable

FFTSize=10240
FFTOverlap="(#FFTSize#-256)"
FFTAttack=0
FFTDecay=100
FreqMin=20
FreqMax=20000
Sensitivity=20
; http://docs.rainmeter.net/manual-beta/plugins/audiolevel

MusicPlayer=None
; Music player process name

FirstBandIndex=1

; Environment variables for settings window
SkinGroup=Ocean
Config=Ocean
ConfigPath=C:\Users\jmsdw\Documents\Rainmeter\Skins\Ocean\Ocean.ini
WriteVariable=Color
LineOnly=0
Angle=0
Invert=0
Channel=Avg
Port=Output
ID=
